let products=[];const $=s=>document.querySelector(s),money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);const statusText={menunggu_konfirmasi:'Menunggu Konfirmasi',diproses:'Diproses',selesai:'Selesai',dibatalkan:'Dibatalkan',pending:'Menunggu Pembayaran'};const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function init(){const m=await (await fetch('/api/me')).json();if(!m.user||m.user.role!=='admin')return location='/login.html';load()}
async function load(){products=await (await fetch('/api/products')).json();const orders=await (await fetch('/api/orders')).json();renderStats(orders);renderOrders(orders);renderProducts()}
function renderStats(orders){const pending=orders.filter(x=>x.status==='menunggu_konfirmasi').length;const processing=orders.filter(x=>x.status==='diproses').length;const revenue=orders.filter(x=>x.status!=='dibatalkan').reduce((a,x)=>a+x.total,0);$('#stats').innerHTML=`<div class="stat"><small>Total Pesanan</small><b>${orders.length}</b></div><div class="stat"><small>Perlu Konfirmasi</small><b>${pending}</b></div><div class="stat"><small>Nilai Pesanan</small><b>${money(revenue)}</b></div>`}
function renderOrders(os){if(!os.length){$('#orders').innerHTML='<div class="panel empty">Belum ada pesanan.</div>';return}$('#orders').innerHTML=`<div class="panel" style="padding:0;overflow:hidden"><table class="admin-table"><thead><tr><th>No</th><th>Produk</th><th>Total</th><th>Pembayaran</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${os.map(o=>`<tr><td>#${o.id}</td><td>${o.items?.map(i=>esc(i.name)+' × '+i.quantity).join('<br>')||'-'}</td><td>${money(o.total)}</td><td>${o.payment_method==='transfer'?'Transfer':'Cash'}</td><td><span class="status-pill ${o.status==='diproses'||o.status==='selesai'?'green':o.status==='dibatalkan'?'red':'yellow'}">${statusText[o.status]||o.status}</span></td><td><div class="order-actions">${o.status==='menunggu_konfirmasi'?`<button class="btn success small" onclick="orderAction(${o.id},'confirm')">✓</button><button class="btn danger small" onclick="orderAction(${o.id},'reject')">✕</button>`:''}${o.status==='diproses'?`<button class="btn small" onclick="orderAction(${o.id},'finish')">Selesai</button>`:'-'}</div></td></tr>`).join('')}</tbody></table></div>`}
function renderProducts(){$('#productList').innerHTML=products.map(p=>`<div class="adminrow"><div><b>${esc(p.name)}</b><br><small style="color:var(--muted)">${money(p.price)} · stok ${p.stock} · ${esc(p.category||'Tanpa kategori')}</small></div><button class="btn small" onclick="edit(${p.id})">Edit</button><button class="btn danger small" onclick="del(${p.id})">Hapus</button></div>`).join('')||'<div class="empty">Belum ada produk.</div>'}
async function orderAction(id,action){const msg=action==='confirm'?'Konfirmasi pembayaran pesanan ini?':action==='reject'?'Tolak pembayaran dan kembalikan stok?':'Tandai pesanan selesai?';if(!confirm(msg))return;const r=await fetch(`/api/admin/orders/${id}/${action}`,{method:'POST'}),d=await r.json();if(!r.ok)return alert(d.error||'Gagal.');load()}
function openForm(p){$('#modal').classList.remove('hidden');$('#productForm').reset();for(const k of ['id','name','description','price','stock','category','image'])$(`#productForm [name="${k}"]`).value=p?.[k]??''}
function closeForm(){$('#modal').classList.add('hidden')}function edit(id){openForm(products.find(p=>p.id===id))}
async function del(id){if(!confirm('Hapus produk?'))return;const r=await fetch('/api/admin/products/'+id,{method:'DELETE'});if(!r.ok)return alert((await r.json()).error||'Gagal');load()}
$('#productForm').onsubmit=async e=>{e.preventDefault();let b=Object.fromEntries(new FormData(e.target)),id=b.id;delete b.id;b.price=Number(b.price);b.stock=Number(b.stock);const r=await fetch('/api/admin/products'+(id?'/'+id:''),{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});if(!r.ok)return alert((await r.json()).error||'Gagal');closeForm();load()};
$('#logout').onclick=async e=>{e.preventDefault();await fetch('/api/logout',{method:'POST'});location='/login.html'};init();
