const {neon}=require("@neondatabase/serverless");const bcrypt=require("bcryptjs");const crypto=require("crypto");const sql=()=>neon(process.env.DATABASE_URL);
const send=(res,c,d)=>{res.statusCode=c;res.setHeader("Content-Type","application/json");res.end(JSON.stringify(d))};
const read=req=>new Promise((ok,bad)=>{let s="";req.on("data",x=>s+=x);req.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(e)}})});
function sign(p){const r=Buffer.from(JSON.stringify(p)).toString("base64url"),s=crypto.createHmac("sha256",process.env.SESSION_SECRET).update(r).digest("base64url");return r+"."+s}
function getUser(req){try{const m=(req.headers.cookie||"").match(/dane=([^;]+)/);if(!m)return null;const[a,b]=decodeURIComponent(m[1]).split("."),s=crypto.createHmac("sha256",process.env.SESSION_SECRET).update(a).digest("base64url");if(b!==s)return null;const p=JSON.parse(Buffer.from(a,"base64url"));return p.exp>Date.now()?p:null}catch{return null}}
let ready=false;async function setup(){if(ready)return;const q=sql();await q`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer')`;await q`CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,name TEXT NOT NULL,description TEXT DEFAULT '',price INTEGER NOT NULL,stock INTEGER NOT NULL DEFAULT 0,image TEXT DEFAULT '',category TEXT DEFAULT '')`;await q`CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id),customer_name TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL,total INTEGER NOT NULL,status TEXT DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW())`;await q`CREATE TABLE IF NOT EXISTS order_items(id SERIAL PRIMARY KEY,order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,product_id INTEGER,name TEXT,price INTEGER,quantity INTEGER)`;const u=await q`SELECT id FROM users WHERE username=${process.env.ADMIN_USERNAME||"admin"} LIMIT 1`;if(!u.length){const h=await bcrypt.hash(process.env.ADMIN_PASSWORD||"change-this-password",10);await q`INSERT INTO users(username,password,role) VALUES(${process.env.ADMIN_USERNAME||"admin"},${h},'admin')`}ready=true}
module.exports=async(req,res)=>{try{await setup();const p=new URL(req.url,"https://x").pathname.replace(/^\/api/,"")||"/",q=sql(),u=getUser(req);
if(req.method==="GET"&&p==="/products")return send(res,200,await q`SELECT * FROM products ORDER BY id DESC`);
if(req.method==="GET"&&p==="/me")return send(res,200,{user:u});
if(req.method==="POST"&&p==="/register"){const b=await read(req);if(!b.username||!b.password||b.password.length<6)return send(res,400,{error:"Password minimal 6 karakter."});try{const h=await bcrypt.hash(b.password,10),r=await q`INSERT INTO users(username,password) VALUES(${b.username},${h}) RETURNING id,username,role`;return send(res,201,{user:r[0]})}catch{return send(res,409,{error:"Username sudah digunakan."})}}
if(req.method==="POST"&&p==="/login"){const b=await read(req),r=await q`SELECT * FROM users WHERE username=${b.username} LIMIT 1`;if(!r.length||!(await bcrypt.compare(b.password||"",r[0].password)))return send(res,401,{error:"Login gagal."});res.setHeader("Set-Cookie",`dane=${encodeURIComponent(sign({id:r[0].id,username:r[0].username,role:r[0].role,exp:Date.now()+604800000}))}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`);return send(res,200,{user:{id:r[0].id,username:r[0].username,role:r[0].role}})}
if(req.method==="POST"&&p==="/logout"){res.setHeader("Set-Cookie","dane=; Path=/; Max-Age=0");return send(res,200,{ok:true})}
if(req.method==="POST"&&p==="/orders"){if(!u)return send(res,401,{error:"Login diperlukan."});const b=await read(req);if(!b.items?.length)return send(res,400,{error:"Keranjang kosong."});const ids=b.items.map(x=>Number(x.id)),ps=await q`SELECT * FROM products WHERE id=ANY(${ids})`;let total=0;for(const x of b.items){const z=ps.find(a=>a.id===Number(x.id));if(!z||z.stock<Number(x.qty))return send(res,400,{error:"Produk atau stok tidak tersedia."});total+=z.price*Number(x.qty)}const o=await q`INSERT INTO orders(user_id,customer_name,phone,address,total) VALUES(${u.id},${b.customerName},${b.phone},${b.address},${total}) RETURNING id`;for(const x of b.items){const z=ps.find(a=>a.id===Number(x.id));await q`INSERT INTO order_items(order_id,product_id,name,price,quantity) VALUES(${o[0].id},${z.id},${z.name},${z.price},${x.qty})`;await q`UPDATE products SET stock=stock-${x.qty} WHERE id=${z.id}`}return send(res,201,{orderId:o[0].id,total})}
if(req.method==="GET"&&p==="/orders"){if(!u)return send(res,401,{error:"Login diperlukan."});const os=u.role==="admin"?await q`SELECT * FROM orders ORDER BY id DESC`:await q`SELECT * FROM orders WHERE user_id=${u.id} ORDER BY id DESC`;for(const o of os)o.items=await q`SELECT * FROM order_items WHERE order_id=${o.id}`;return send(res,200,os)}
if(p.startsWith("/admin/products")){if(!u||u.role!=="admin")return send(res,403,{error:"Akses admin diperlukan."});const id=p.split("/")[3];if(req.method==="POST"){const b=await read(req);const r=await q`INSERT INTO products(name,description,price,stock,image,category) VALUES(${b.name},${b.description||""},${b.price},${b.stock||0},${b.image||""},${b.category||""}) RETURNING *`;return send(res,201,r[0])}if(req.method==="PUT"){const b=await read(req);const r=await q`UPDATE products SET name=${b.name},description=${b.description||""},price=${b.price},stock=${b.stock},image=${b.image||""},category=${b.category||""} WHERE id=${id} RETURNING *`;return send(res,200,r[0])}if(req.method==="DELETE"){await q`DELETE FROM products WHERE id=${id}`;return send(res,200,{ok:true})}}
return send(res,404,{error:"Not found"})}catch(e){console.error(e);return send(res,500,{error:"Server error"})}};